<a href="https://colab.research.google.com/github/barathturing/final-hack/blob/main/rf_wo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
#Reading files using pandas
df1=pd.read_csv("/content/drive/MyDrive/TrainData/Train_Claim.csv")
df2=pd.read_csv("/content/drive/MyDrive/TrainData/Train_Demographics.csv")
df3=pd.read_csv("/content/drive/MyDrive/TrainData/Train_Policy.csv")
df4=pd.read_csv("/content/drive/MyDrive/TrainData/Train_Vehicle_new.csv")
df5=pd.read_csv("/content/drive/MyDrive/TrainData/Traindata_with_Target.csv")

In [ ]:
#checking shape of each datasets
print("df1:",df1.shape)
print("df2:",df2.shape)
print("df3:",df3.shape)
print("df4:",df4.shape)
print("df5:",df5.shape)

df1: (28836, 19)
df2: (28836, 10)
df3: (28836, 10)
df4: (28836, 5)
df5: (28836, 2)


In [ ]:
#merging all datasets based on "CstomerID"
sample_1=pd.merge(df1,df2)
sample_2=pd.merge(sample_1,df3)
sample_3=pd.merge(sample_2,df4)
master=pd.merge(sample_3,df5)

In [ ]:
master.head()

In [ ]:
# Making a list of missing value types
missing_values = ["MISSEDDATA","NA","?","MISSINGVALUE","???",-5,"MISSINGVAL",-1,"N/A","na"]

In [ ]:
#we create one missing values list by using that if that comes in any place we replace it with nan
for column in master.columns:
    for missing in missing_values:
        master[column] = np.where(master[column]==missing, np.NaN, master[column])

In [ ]:
master.isnull().sum()

In [ ]:
master.info()

In [ ]:
#checking missing values percent using isnull function 
master.isnull().sum()/len(master)*100 

# imputing missing values for both **numeric** and catagorical

In [ ]:
#by using hist graph we can see how data distributed
master.hist(bins=50, figsize=(15, 12))
plt.show()

In [ ]:
##  Replace NAN values with most occured category in TypeOfCollission
Mode_Category = master["TypeOfCollission"].mode()[0]
master["TypeOfCollission"].fillna(Mode_Category,inplace=True)

In [ ]:
##  Replace NAN values with median in IncidentTime
median=master['IncidentTime'].median()
master['IncidentTime'].fillna(median,inplace=True)

In [ ]:
#drop huge no of missing value data 
master.drop(['PropertyDamage','Country'],axis=1,inplace=True)

In [ ]:
##  Replace NAN values with median  in witness
median_1=master['Witnesses'].median()
master['Witnesses'].fillna(median_1,inplace=True)

In [ ]:
##  Replace NAN values with most occured category in police report
Mode_Category_1 = master["PoliceReport"].mode()[0]
master["PoliceReport"].fillna(Mode_Category_1,inplace=True)

In [ ]:
###  Replace NAN values with median in AmountOfTotalClaim
median_2=master['AmountOfTotalClaim'].median()
master['AmountOfTotalClaim'].fillna(median_2,inplace=True)

In [ ]:
##  Replace NAN values with most occured category in gender
Mode_Category_2 = master["InsuredGender"].mode()[0]
master["InsuredGender"].fillna(Mode_Category_2,inplace=True)

In [ ]:
master.drop(['CustomerID','VehicleID','InsurancePolicyNumber'],axis=1,inplace=True)

In [ ]:
###  Replace NAN values with median in PolicyAnnualPremium 
median_3=master['PolicyAnnualPremium'].median()
master['PolicyAnnualPremium'].fillna(median_3,inplace=True)

In [ ]:
##  Replace NAN values with most occured category in VehicleMake
Mode_Category_3 = master["VehicleMake"].mode()[0]
master["VehicleMake"].fillna(Mode_Category_3,inplace=True)

In [ ]:
master.isnull().sum().any()

In [ ]:
master.info()

In [ ]:
#two numerical feature shows object type change type to numerical
master['AmountOfTotalClaim'] = master['AmountOfTotalClaim'].astype('int')
master['Witnesses']=master['Witnesses'].astype('int')

In [ ]:
master['ReportedFraud'].value_counts()

# Visuvalization 

In [ ]:
plt.style.use('fivethirtyeight')
ax = sns.countplot(x='ReportedFraud', data=master, hue='ReportedFraud')

In [ ]:
#function for crosstabs
def cross_tab(x,y):
    crtab = pd.crosstab(master[x], master[y])
    return crtab

In [ ]:
#insuredgender vs ReportedFraud
cross_tab('InsuredGender','ReportedFraud')

In [ ]:
sns.catplot(data=master,x='InsuredGender',hue='ReportedFraud',kind='count')

In [ ]:
#InsurancePolicyState v/s ReportedFraud
cross_tab('InsurancePolicyState','ReportedFraud')

In [ ]:
sns.catplot(data=master,x='InsurancePolicyState',hue='ReportedFraud',kind='count')

In [ ]:
#incidenttype vs ReportedFraud
sns.catplot(data=master,x='TypeOfIncident',hue='ReportedFraud',kind='count')
plt.xticks(rotation = 90)


In [ ]:
#insured education level v/s ReportedFraud
cross_tab('InsuredEducationLevel','ReportedFraud')

In [ ]:
sns.catplot(data=master,x='InsuredEducationLevel',hue='ReportedFraud',kind='count')
plt.xticks(rotation = 90)


In [ ]:
#insured relationship v/s ReportedFraud
cross_tab('InsuredRelationship','ReportedFraud')

In [ ]:
sns.catplot(data=master,x='InsuredRelationship',hue='ReportedFraud',kind='count')
plt.xticks(rotation = 90)

In [ ]:
#authorities contacted v/s fraud reported

cross_tab('AuthoritiesContacted','ReportedFraud')

In [ ]:
sns.catplot(data=master,x='AuthoritiesContacted',hue='ReportedFraud',kind='count')
plt.xticks(rotation = 90)

In [ ]:
sns.catplot(data=master,x='IncidentCity',hue='ReportedFraud',kind='count')
plt.xticks(rotation = 90)

In [ ]:
plt.figure(figsize = (12, 5))
df_temp = master[master.ReportedFraud == 'Y']
sns.set_style('darkgrid')
sns.countplot(x = 'VehicleYOM', data = master)
plt.ylabel('No. of fraud reported')
plt.title('ReportedFraud VS VehicleYOM')
plt.xticks(rotation = 90)

# catogorical to nuerical

In [ ]:
master.select_dtypes(include='object').describe().T

In [ ]:
master=master.drop(columns=['DateOfIncident','IncidentAddress','DateOfPolicyCoverage','InsuredZipCode'])

In [ ]:
#catogorical columns 
categorical_columns = master.select_dtypes(include=['object']).columns
categorical_columns

Index(['TypeOfIncident', 'TypeOfCollission', 'SeverityOfIncident',
       'AuthoritiesContacted', 'IncidentState', 'IncidentCity', 'PoliceReport',
       'InsuredGender', 'InsuredEducationLevel', 'InsuredOccupation',
       'InsuredHobbies', 'InsurancePolicyState', 'Policy_CombinedSingleLimit',
       'InsuredRelationship', 'VehicleMake', 'VehicleModel', 'ReportedFraud'],
      dtype='object')

In [ ]:
master.shape

(28836, 33)

In [ ]:
from sklearn.preprocessing import LabelEncoder
label= LabelEncoder()

for colum in categorical_columns:
    master[colum]= label.fit_transform(master[colum])  

In [ ]:
master.head()

In [ ]:
master.dtypes

In [ ]:
x=master.drop('ReportedFraud',axis=1)
y=master['ReportedFraud']
x.shape

(28836, 32)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mm=MinMaxScaler()
train_scaled=pd.DataFrame(mm.fit_transform(x))

In [ ]:
train_scaled.head()

# test data

In [ ]:
df1=pd.read_csv("/content/drive/MyDrive/TestData/Test_Claim.csv")
df2=pd.read_csv("/content/drive/MyDrive/TestData/Test_Demographics.csv")
df3=pd.read_csv("/content/drive/MyDrive/TestData/Test_Policy.csv")
df4=pd.read_csv("/content/drive/MyDrive/TestData/Test.csv")
df5=pd.read_csv("/content/drive/MyDrive/TestData/Test_Vehicle_new.csv")

In [ ]:
print(df1.shape)
print(df2.shape)
print(df3.shape)
print(df4.shape)
print(df5.shape)

(8912, 19)
(8912, 10)
(8912, 10)
(8912, 1)
(8912, 5)


In [ ]:
#merging all datasets based on "CstomerID"
sample_1=pd.merge(df1,df2)
sample_2=pd.merge(sample_1,df3)
sample_3=pd.merge(sample_2,df4)
test=pd.merge(sample_3,df5)

In [ ]:
test.head()

In [ ]:
# Making a list of missing value types
missing_values = ["MISSEDDATA","NA","?","MISSINGVALUE","???",-5,"MISSINGVAL",-1,"N/A","na"]

In [ ]:
#we create one missing values list by using that if that comes in any place we replace it with nan
for column in test.columns:
    for missing in missing_values:
        test[column] = np.where(test[column]==missing, np.NaN, test[column])

In [ ]:
test.isnull().sum()

In [ ]:
##  Replace NAN values with most occured category in TypeOfCollission
Mode_Category = test["TypeOfCollission"].mode()[0]
test["TypeOfCollission"].fillna(Mode_Category,inplace=True)

##  Replace NAN values with median in IncidentTime
median=test['IncidentTime'].median()
test['IncidentTime'].fillna(median,inplace=True)

##  Replace NAN values with median  in witness
median_1=master['Witnesses'].median()
master['Witnesses'].fillna(median_1,inplace=True)

#drop huge no of missing value data 
test.drop(['PropertyDamage','Country'],axis=1,inplace=True)

##  Replace NAN values with most occured category in police report
Mode_Category_1 = test["PoliceReport"].mode()[0]
test["PoliceReport"].fillna(Mode_Category_1,inplace=True)

###  Replace NAN values with median in AmountOfTotalClaim
median_2=test['AmountOfTotalClaim'].median()
test['AmountOfTotalClaim'].fillna(median_2,inplace=True)

##  Replace NAN values with most occured category in gender
Mode_Category_2 = test["InsuredGender"].mode()[0]
test["InsuredGender"].fillna(Mode_Category_2,inplace=True)

###  Replace NAN values with median in PolicyAnnualPremium 
median_3=test['PolicyAnnualPremium'].median()
test['PolicyAnnualPremium'].fillna(median_3,inplace=True)

##  Replace NAN values with most occured category in VehicleMake
Mode_Category_3 = test["VehicleMake"].mode()[0]
test["VehicleMake"].fillna(Mode_Category_3,inplace=True)

In [ ]:
test['AmountOfTotalClaim'] = test['AmountOfTotalClaim'].astype('int')

In [ ]:
test=test.drop(columns=['InsurancePolicyNumber','DateOfIncident','IncidentAddress','DateOfPolicyCoverage','InsuredZipCode','VehicleID'])

In [ ]:
customerid=test['CustomerID']
test.drop(['CustomerID'],axis=1,inplace=True)

In [ ]:
#catogorical columns 
categorical_columns = test.select_dtypes(include=['object']).columns
categorical_columns

In [ ]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

for columns in categorical_columns:
    test[columns]= label.fit_transform(test[columns]) 

In [ ]:
test.dtypes

In [ ]:
test.shape

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mm=MinMaxScaler()
test_scaled=pd.DataFrame(mm.fit_transform(test))

In [ ]:
x.head()

In [ ]:
print(x.shape)
print(test.shape)

In [ ]:
train_scaled.head()

In [ ]:
test_scaled.head()

In [ ]:
#from sklearn.model_selection import train_test_split
#x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30905,random_state=42)

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
rf=RandomForestClassifier()
rf.fit(train_scaled,y)

RandomForestClassifier()

In [ ]:
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
ada=AdaBoostClassifier()
ada.fit(train_scaled,y)

AdaBoostClassifier()

In [ ]:
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
gb=GradientBoostingClassifier()
gb.fit(train_scaled,y)

GradientBoostingClassifier()

In [ ]:
#param_grid = {'n_estimators' : [50, 100, 150, 200],
#              'max_features' : [2, 3, 4,5],
 #             'max_depth' : [3, 5, 7, 2],
   #           'min_samples_split' : [2, 5, 8, 4]} ##

In [ ]:
#GSV = GridSearchCV(rf,param_grid,verbose=3,n_jobs=4)
#GSV.fit(train_scaled, y)

In [ ]:
#GSV.best_params_

In [ ]:
#random=RandomForestClassifier(n_estimators=300,max_depth=7,min_samples_split=5,max_features=4)
#random.fit(train_scaled,y)

In [ ]:
y_pred=rf.predict(test_scaled)
#y1_pred=ada.predict(test_scaled)
#y2_pred=gb.predict(test_scaled)

In [ ]:
#y_new=random.predict(test_scaled)

In [ ]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
y1_pred

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
y2_pred

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
result=pd.DataFrame({'CustomerID':customerid,'ReportedFraud':y_pred})


In [ ]:
result['ReportedFraud'].value_counts()

0    7599
1    1313
Name: ReportedFraud, dtype: int64

In [ ]:
result.to_csv('barath_new4.csv',index=False)